---
galaxy_info:
  author: Harisfazillah Jamel
  description: Sovereign Gitea GitOps Core Quadlet Deployment
  company: DSOM Protocol
  license: GPL-3.0-only
  min_ansible_version: "2.14"
  platforms:
    - name: Ubuntu
      versions:
        - all
dependencies: []
