# .gitbook.yaml
# ==============================================================================
# 📜 DSOM GitBook Orchestration (Cloud Config)
# Protocol: Deep State of Mind (DSOM) For My AI Protocol
# ==============================================================================
root: ./
structure:
  readme: README.md
  summary: SUMMARY.md

# Inclusion of Brain Artifacts as tracked content
content:
  - .agent/brain/*.md
  - docs/*.md
  - SUMMARY.md
  - README.md

language: en-gb

theme:
  style: documentation
  show_level: true

