"""
Unit tests for the Native Python OpenWiki Emulator (tools/openwiki_emulator.py).

Verifies that:
1. `get_timestamp()` produces valid ISO format timestamp strings.
2. `generate_skeleton()` returns valid OKF YAML frontmatter documentation.
3. `generate_last_update_json()` outputs valid JSON metrics.
4. `generate_instructions_md()` returns the expected generated-file marker.
5. `generate_page()` correctly formats OKF frontmatter + Markdown body pages.
6. `PLANNED_PAGES` contains well-formed entries for every planned wiki page.
7. `cmd_init()` materializes the skeleton, metadata, and all planned pages on disk.
"""
import contextlib
import io
import json
import pathlib
import sys
import tempfile
import unittest
from unittest import mock

import yaml

# Ensure tools/ is on Python path
REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "tools"))

import openwiki_emulator  # type: ignore # noqa: E402


EXPECTED_PLANNED_PAGE_PATHS = {
    "quickstart.md",
    "architecture/overview.md",
    "governance/agent-operation.md",
    "memory/session-and-palace.md",
    "automation/ansible-baseline.md",
    "automation/tools-and-privacy.md",
    "integrations/mcp-and-ci.md",
    "publishing/documentation-delivery.md",
    "quality/verification.md",
}


class OpenWikiEmulatorTests(unittest.TestCase):
    """Test OpenWiki emulator generator functions."""

    def test_get_timestamp_format(self):
        ts = openwiki_emulator.get_timestamp()
        self.assertTrue(ts.endswith("Z"))
        self.assertIn("T", ts)

    def test_generate_skeleton_contains_okf_frontmatter(self):
        skeleton = openwiki_emulator.generate_skeleton()
        self.assertTrue(skeleton.startswith("---"))
        self.assertIn("title: \"OpenWiki Documentation Skeleton & Subsystem Index\"", skeleton)

    def test_generate_last_update_json_parses(self):
        json_str = openwiki_emulator.generate_last_update_json()
        data = json.loads(json_str)
        self.assertEqual(data["status"], "success")
        self.assertIn("updatedAt", data)


class GenerateInstructionsMdTests(unittest.TestCase):
    """Test the generated-file marker used by INSTRUCTIONS.md."""

    def test_generate_instructions_md_marker(self):
        content = openwiki_emulator.generate_instructions_md()
        self.assertEqual(content, "<!-- OPENWIKI:GENERATED BY DSOM PYTHON EMULATOR -->\n")

    def test_generate_instructions_md_returns_str(self):
        self.assertIsInstance(openwiki_emulator.generate_instructions_md(), str)


class GeneratePageTests(unittest.TestCase):
    """Test the `generate_page()` OKF page formatter."""

    def test_generate_page_starts_with_frontmatter_fence(self):
        page = openwiki_emulator.generate_page(
            title="Test Title",
            timestamp="2026-08-10T12:30:20Z",
            topics=["a", "b", "c"],
            description="Test description",
            content_markdown="# Heading\n\nBody text.",
        )
        self.assertTrue(page.startswith("---\n"))

    def test_generate_page_includes_all_frontmatter_fields(self):
        page = openwiki_emulator.generate_page(
            title="Test Title",
            timestamp="2026-08-10T12:30:20Z",
            topics=["a", "b", "c"],
            description="Test description",
            content_markdown="# Heading\n\nBody text.",
        )
        self.assertIn("okf_version: 0.1", page)
        self.assertIn('type: "documentation"', page)
        self.assertIn('title: "Test Title"', page)
        self.assertIn('timestamp: "2026-08-10T12:30:20Z"', page)
        self.assertIn('topics: ["a", "b", "c"]', page)
        self.assertIn('description: "Test description"', page)

    def test_generate_page_strips_leading_and_trailing_whitespace_from_body(self):
        page = openwiki_emulator.generate_page(
            title="T",
            timestamp="TS",
            topics=["x"],
            description="D",
            content_markdown="\n\n  # Heading\n\nBody text.\n\n",
        )
        self.assertTrue(page.endswith("# Heading\n\nBody text.\n"))
        self.assertNotIn("\n\n\n# Heading", page)

    def test_generate_page_frontmatter_is_valid_yaml(self):
        page = openwiki_emulator.generate_page(
            title="Test Title",
            timestamp="2026-08-10T12:30:20Z",
            topics=["a", "b", "c"],
            description="Test description",
            content_markdown="Body content.",
        )
        parts = page.split("---", 2)
        self.assertEqual(len(parts), 3)
        meta = yaml.safe_load(parts[1])
        self.assertEqual(meta["okf_version"], 0.1)
        self.assertEqual(meta["type"], "documentation")
        self.assertEqual(meta["title"], "Test Title")
        self.assertEqual(meta["timestamp"], "2026-08-10T12:30:20Z")
        self.assertEqual(meta["topics"], ["a", "b", "c"])
        self.assertEqual(meta["description"], "Test description")

    def test_generate_page_empty_topics_list(self):
        page = openwiki_emulator.generate_page(
            title="T",
            timestamp="TS",
            topics=[],
            description="D",
            content_markdown="content",
        )
        self.assertIn("topics: []", page)

    def test_generate_page_single_topic(self):
        page = openwiki_emulator.generate_page(
            title="T",
            timestamp="TS",
            topics=["solo"],
            description="D",
            content_markdown="content",
        )
        self.assertIn('topics: ["solo"]', page)

    def test_generate_page_whitespace_only_body_collapses_to_empty(self):
        page = openwiki_emulator.generate_page(
            title="T",
            timestamp="TS",
            topics=["x"],
            description="D",
            content_markdown="   \n\n   ",
        )
        parts = page.split("---", 2)
        self.assertEqual(len(parts), 3)
        # Only the boilerplate newlines remain once the body is stripped away.
        self.assertEqual(parts[2], "\n\n")

    def test_generate_page_returns_str(self):
        result = openwiki_emulator.generate_page(
            title="T", timestamp="TS", topics=["x"], description="D", content_markdown="c"
        )
        self.assertIsInstance(result, str)


class PlannedPagesTests(unittest.TestCase):
    """Test the `PLANNED_PAGES` registry that drives `cmd_init()`."""

    def test_planned_pages_keys_match_expected_paths(self):
        self.assertEqual(set(openwiki_emulator.PLANNED_PAGES.keys()), EXPECTED_PLANNED_PAGE_PATHS)

    def test_planned_pages_count(self):
        self.assertEqual(len(openwiki_emulator.PLANNED_PAGES), 9)

    def test_planned_pages_entries_have_required_fields(self):
        for relative_path, info in openwiki_emulator.PLANNED_PAGES.items():
            with self.subTest(page=relative_path):
                self.assertIsInstance(info["title"], str)
                self.assertTrue(info["title"].strip())
                self.assertIsInstance(info["description"], str)
                self.assertTrue(info["description"].strip())
                self.assertIsInstance(info["topics"], list)
                self.assertTrue(info["topics"])
                self.assertTrue(all(isinstance(t, str) for t in info["topics"]))
                self.assertIsInstance(info["content"], str)
                self.assertTrue(info["content"].strip().startswith("#"))

    def test_planned_pages_topics_all_include_openwiki(self):
        for relative_path, info in openwiki_emulator.PLANNED_PAGES.items():
            with self.subTest(page=relative_path):
                self.assertEqual(info["topics"][0], "openwiki")

    def test_planned_pages_render_to_valid_okf_documents(self):
        timestamp = "2026-08-10T12:30:20Z"
        for relative_path, info in openwiki_emulator.PLANNED_PAGES.items():
            with self.subTest(page=relative_path):
                page = openwiki_emulator.generate_page(
                    title=info["title"],
                    timestamp=timestamp,
                    topics=info["topics"],
                    description=info["description"],
                    content_markdown=info["content"],
                )
                parts = page.split("---", 2)
                self.assertEqual(len(parts), 3)
                meta = yaml.safe_load(parts[1])
                self.assertEqual(meta["title"], info["title"])
                self.assertEqual(meta["description"], info["description"])
                self.assertEqual(meta["topics"], info["topics"])
                self.assertEqual(meta["timestamp"], timestamp)


class CmdInitTests(unittest.TestCase):
    """Test that `cmd_init()` materializes the full OpenWiki tree on disk."""

    def _run_cmd_init_in_tmp_dir(self):
        """Run cmd_init() against an isolated temp directory and return its path."""
        tmpdir = tempfile.TemporaryDirectory()
        self.addCleanup(tmpdir.cleanup)
        fake_openwiki_dir = pathlib.Path(tmpdir.name) / "openwiki"
        patcher = mock.patch.object(openwiki_emulator, "OPENWIKI_DIR", fake_openwiki_dir)
        patcher.start()
        self.addCleanup(patcher.stop)
        with contextlib.redirect_stdout(io.StringIO()):
            openwiki_emulator.cmd_init()
        return fake_openwiki_dir

    def test_cmd_init_creates_metadata_files(self):
        fake_dir = self._run_cmd_init_in_tmp_dir()
        self.assertTrue((fake_dir / "_skeleton.md").is_file())
        self.assertTrue((fake_dir / ".last-update.json").is_file())
        self.assertTrue((fake_dir / "INSTRUCTIONS.md").is_file())

    def test_cmd_init_creates_every_planned_page(self):
        fake_dir = self._run_cmd_init_in_tmp_dir()
        for relative_path in openwiki_emulator.PLANNED_PAGES:
            with self.subTest(page=relative_path):
                self.assertTrue((fake_dir / relative_path).is_file())

    def test_cmd_init_creates_nested_directories_on_demand(self):
        # The per-page loop calls dest_file.parent.mkdir(parents=True, exist_ok=True)
        # independently of ensure_openwiki_dirs(); confirm nested dirs land correctly.
        fake_dir = self._run_cmd_init_in_tmp_dir()
        for relative_path in openwiki_emulator.PLANNED_PAGES:
            nested_dir = (fake_dir / relative_path).parent
            with self.subTest(page=relative_path):
                self.assertTrue(nested_dir.is_dir())

    def test_cmd_init_generated_page_matches_planned_metadata(self):
        fake_dir = self._run_cmd_init_in_tmp_dir()
        info = openwiki_emulator.PLANNED_PAGES["quickstart.md"]
        content = (fake_dir / "quickstart.md").read_text(encoding="utf-8")
        self.assertIn(f'title: "{info["title"]}"', content)
        self.assertIn(f'description: "{info["description"]}"', content)
        parts = content.split("---", 2)
        meta = yaml.safe_load(parts[1])
        self.assertEqual(meta["topics"], info["topics"])

    def test_cmd_init_last_update_json_is_valid(self):
        fake_dir = self._run_cmd_init_in_tmp_dir()
        data = json.loads((fake_dir / ".last-update.json").read_text(encoding="utf-8"))
        self.assertEqual(data["status"], "success")
        self.assertEqual(data["pagesCompiled"], 10)
        self.assertIn("updatedAt", data)

    def test_cmd_init_instructions_md_marker(self):
        fake_dir = self._run_cmd_init_in_tmp_dir()
        content = (fake_dir / "INSTRUCTIONS.md").read_text(encoding="utf-8")
        self.assertEqual(content, "<!-- OPENWIKI:GENERATED BY DSOM PYTHON EMULATOR -->\n")

    def test_cmd_init_is_idempotent_when_run_twice(self):
        # Re-running cmd_init() against the same directory should not fail and
        # should not duplicate/corrupt any of the planned pages.
        tmpdir = tempfile.TemporaryDirectory()
        self.addCleanup(tmpdir.cleanup)
        fake_openwiki_dir = pathlib.Path(tmpdir.name) / "openwiki"
        with mock.patch.object(openwiki_emulator, "OPENWIKI_DIR", fake_openwiki_dir):
            with contextlib.redirect_stdout(io.StringIO()):
                openwiki_emulator.cmd_init()
                openwiki_emulator.cmd_init()
            for relative_path in openwiki_emulator.PLANNED_PAGES:
                self.assertTrue((fake_openwiki_dir / relative_path).is_file())


if __name__ == "__main__":
    unittest.main()
