---
- name: Reload systemd user daemon and restart gitea-stack
  ansible.builtin.systemd_service:
    name: gitea-stack.service
    state: restarted
    daemon_reload: true
    scope: user
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ ansible_user_uid }}"
