---
- name: TLS | Ensure local certs directory exists
  ansible.builtin.file:
    path: "{{ playbook_dir }}/../vault/generated"
    state: directory
    mode: "0700"
  delegate_to: localhost
  run_once: true
  become: false

- name: TLS | Ensure target cert directory exists
  ansible.builtin.file:
    path: "~/.config/gitea/certs"
    state: directory
    mode: "0755"
  become: false
